SELECT CUSTOMER_ID, STATUS FROM YUKENDHIRAN.ORDER_BASE.T_CUSTOMER WHERE STATUS = 'ACTIVE' and CUSTOMER_ID = 'CUST0001';
SELECT ORDER_ID, ORDER_DATE, CUSTOMER_ID, STATUS FROM YUKENDHIRAN.ORDER_BASE.T_SALES_ORDER_HEADER WHERE STATUS = 'OPEN' and ORDER_ID = 'ORD0009';
SELECT ORDER_ID,
       ORDER_DATE,
       CUSTOMER_ID,
       INVOICE_DATE,
       TAX_AMOUNT,
       TOTAL_AMOUNT,
       DISCOUNT,
       FINAL_INVOICE_AMT
    FROM YUKENDHIRAN.ORDER_BASE.T_INVOICE
    WHERE ORDER_ID = 'ORD0009';

