SELECT ITEM_ID FROM Y_SIM_BOM.BMATHUB_XFRM.V_ITEM_DETAIL_ROOT WHERE DELETE_IND = FALSE and ITEM_CLASS_NM = 'UPI_DIE_PREP';
SELECT ITEM, BOM_NUM FROM Y_SIM_BOM.BMATHUB_ANALYSIS.V_SIM_BOM;
SELECT INPUT_ITEM_ID, LOC FROM Y_SIM_BOM.BMATHUB_XFRM.V_ORIG_BOM;