CALL YUKENDHIRAN.ORDER_BASE.P_UPDATE_META_DATA();
SELECT * FROM TABLE(YUKENDHIRAN.ORDER_BASE.F_PROMOTION_DISCOUNT());
CALL YUKENDHIRAN.ORDER_BASE.P_INVOICE_GENERATE();
SELECT 
  ORDER_ID,
  ORDER_DATE,
  CUSTOMER_ID,
  ITEM_ID,
  QTY,
  PRICE,
  TOTAL_AMOUNT,
  CREATE_DATE,
  CREATE_USER
FROM ORDER_XFRM.V_SALES_ORDER_DETAIL
WHERE ORDER_DATE > CURRENT_DATE;

SELECT 
  ORDER_ID,
  ORDER_DATE,
  CUSTOMER_ID,
  INVOICE_DATE,
  TAX_AMOUNT,
  TOTAL_AMOUNT,
  DISCOUNT,
  FINAL_INVOICE_AMT,
  CREATE_DATE,
  CREATE_USER 
FROM ORDER_ANALYSIS.V_INVOICE;

truncate table ORDER_BASE.T_CUSTOMER;
SELECT 
  CUSTOMER_ID,
  ADDRESS,
  PHONE_NO,
  CATEGORY,
  STATUS,
  CREATE_DATE,
  CREATE_USER,
  TOTAL_ORDERS,
  TOTAL_INVOICE_AMOUNT,
  LOYALTY_POINTS
FROM ORDER_BASE.T_CUSTOMER;

SELECT * FROM ORDER_XFRM.V_CUSTOMER;

truncate table ORDER_BASE.T_SALES_ORDER_HEADER;
SELECT 
  ORDER_ID,
  ORDER_DATE,
  STATUS,
  CUSTOMER_ID,
  COUPON,
  CREATE_DATE,
  CREATE_USER,
  ITEM_COUNT,
  TOTAL_AMOUNT,
  DISCOUNT
FROM ORDER_BASE.T_SALES_ORDER_HEADER;

SELECT * FROM ORDER_XFRM.V_SALES_ORDER_HEADER;

truncate table ORDER_BASE.T_SALES_ORDER_DETAIL;
SELECT 
  ORDER_ID,
  ORDER_DATE,
  CUSTOMER_ID,
  ITEM_ID,
  QTY,
  PRICE,
  CREATE_DATE,
  CREATE_USER
FROM ORDER_BASE.T_SALES_ORDER_DETAIL;

SELECT * FROM ORDER_XFRM.V_SALES_ORDER_DETAIL;

truncate table ORDER_BASE.T_INVOICE;
select * from ORDER_xfrm.V_PROMOTION;