CREATE SCHEMA MASTER_DATA;
CREATE SCHEMA BMATHUB_BASE;
CREATE SCHEMA BMATHUB_XFRM;
CREATE SCHEMA BMATHUB_ANALYSIS;

CREATE OR REPLACE PROCEDURE MASTER_ROOT_MAINTAIN()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    COPY INTO Y_SIM_BOM.MASTER_DATA.ITEM (ITEM_ID, ITEM_CLASS_NM, ITEM_DSC, DELETE_IND)
FROM @~/Documents/snowflake/item.csv
FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1);
    COPY INTO Y_SIM_BOM.MASTER_DATA.LOCATION (ITEM_ID, ITEM_CLASS_NM, LOCATION_ID)
FROM @~/Documents/snowflake/location.csv
FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1);
    COPY INTO Y_SIM_BOM.MASTER_DATA.ORIG_BOM (INPUT_ITEM_ID, ITEM_CLASS_NM, OUTPUT_ITEM_ID, LOC)
FROM @~/Documents/snowflake/orig_bom.csv
FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1);
    RETURN 'Data loaded successfully.';
END;
$$;
