CREATE SCHEMA MASTER_DATA;
CREATE SCHEMA BMATHUB_BASE;
CREATE SCHEMA BMATHUB_XFRM;
CREATE SCHEMA BMATHUB_ANALYSIS;
call Y_SIM_BOM.BMATHUB_BASE.P_MASTER_ROOT_MAINTAIN();
call Y_SIM_BOM.BMATHUB_BASE.P_BMATHUB_BASE_P_ROOT_CORE_BUILD();
