CREATE 
OR REPLACE FUNCTION PURCHASE_BASE.F_PURCHASE_SUPPLIER_RANK() RETURNS TABLE (
  SUPPLIER_ID VARCHAR(20), 
  PRIORITY_RANK INT, 
  PROCUREMENT_COST FLOAT, 
  LEAD_TIME INT
) AS $$ 
SELECT 
  sup.SUPPLIER_ID, 
  RANK() OVER (
    ORDER BY 
      pd.PROCUREMENT_COST ASC, 
      sup.LEAD_TIME ASC
  ) AS PRIORITY_RANK, 
  pd.PROCUREMENT_COST, 
  sup.LEAD_TIME 
FROM 
  PURCHASE_XFRM.V_SUPPLIER_HDR sup 
  INNER JOIN PURCHASE_XFRM.V_PURCHASE_DETAIL pd ON pd.SUPPLIER_ID = sup.SUPPLIER_ID $$;
SELECT 
  * 
FROM 
  TABLE(
    PURCHASE_BASE.F_PURCHASE_SUPPLIER_RANK()
  );