INSERT INTO YUKENDHIRAN.ORDER_BASE.T_CUSTOMER (
  CUSTOMER_ID, 
  ADDRESS, 
  PHONE_NO, 
  CATEGORY, 
  STATUS, 
  CREATE_DATE, 
  CREATE_USER
)
SELECT 
  'CUST' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 4, '0') AS CUSTOMER_ID,
  'Address ' || SEQ4() AS ADDRESS,
  '555-01' || LPAD(SEQ4() % 10000, 4, '0') AS PHONE_NO,
  CASE 
    WHEN SEQ4() % 5 = 0 THEN 'GOLD'
    WHEN SEQ4() % 5 = 1 THEN 'SILVER'
    WHEN SEQ4() % 5 = 2 THEN 'BRONZE'
    ELSE 'REGULAR'
  END AS CATEGORY,
  CASE 
    WHEN SEQ4() % 2 = 0 THEN 'ACTIVE'
    ELSE 'INACTIVE'
  END AS STATUS,
  DATEADD(DAY, -((SEQ4() % 120) + 30), CURRENT_DATE) AS CREATE_DATE,
  CASE 
    WHEN SEQ4() % 10 = 0 THEN 'USER_A'
    WHEN SEQ4() % 10 = 1 THEN 'USER_B'
    WHEN SEQ4() % 10 = 2 THEN 'USER_C'
    WHEN SEQ4() % 10 = 3 THEN 'USER_D'
    WHEN SEQ4() % 10 = 4 THEN 'USER_E'
    WHEN SEQ4() % 10 = 5 THEN 'USER_F'
    WHEN SEQ4() % 10 = 6 THEN 'USER_G'
    WHEN SEQ4() % 10 = 7 THEN 'USER_H'
    WHEN SEQ4() % 10 = 8 THEN 'USER_I'
    ELSE 'USER_J'
  END AS CREATE_USER
FROM TABLE(GENERATOR(ROWCOUNT => 100));
