CREATE VIEW IF NOT EXISTS Y_SIM_BOM.BMATHUB_ANALYSIS.V_SIM_BOM AS
SELECT 
    sb.INPUT_ITEM_ID AS ITEM_ID,
    idr.ITEM_ID AS ANCHOR_ITEM_ID,
    sb.BOM_NUM,
    sb.LOC,
    idr.ITEM_DSC AS DESCRIP
FROM
    Y_SIM_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE sb 
    JOIN Y_SIM_BOM.BMATHUB_XFRM.V_ITEM_DETAIL_ROOT idr ON sb.INPUT_ITEM_ID = idr.ITEM_ID;
