CREATE OR REPLACE VIEW Y_SIM_BOM.BMATHUB_ANALYSIS.V_SIM_BOM AS
SELECT 
  sb.ITEM,
  ANCHOR_ITEM_ID,
  sb.BOM_NUM,
  sb.LOC,
  idr.ITEM_DSC AS DESCRIP
FROM
  Y_SIM_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE sb 
  INNER JOIN Y_SIM_BOM.BMATHUB_XFRM.V_ITEM_DETAIL_ROOT idr ON sb.ITEM = idr.ITEM_ID;
