CREATE 
OR REPLACE FUNCTION YUKENDHIRAN.ORDER_BASE.F_PROMOTION_DISCOUNT() RETURNS TABLE (
  CUSTOMER_ID VARCHAR(100), 
  ORDER_ID VARCHAR(100),
  DISCOUNT NUMBER(10, 2) DEFAULT 0
) AS $$ 
SELECT 
  coc.CUSTOMER_ID,
  coc.ORDER_ID,
  CASE 
    WHEN p.PROMOTION_TYPE = 'DISCOUNT' THEN coc.TOTAL_AMOUNT * p.PROMOTION_VALUE / 100 
    WHEN coc.CATEGORY = 'REGULAR' THEN coc.TOTAL_AMOUNT * p.PROMOTION_VALUE 
    ELSE 0 
  END AS DISCOUNT 
FROM 
  (
    SELECT 
      cu.CUSTOMER_ID,
      soh.COUPON,
      soh.ORDER_ID,
      cu.CATEGORY,
      soh.TOTAL_AMOUNT
    FROM 
      YUKENDHIRAN.ORDER_ANALYSIS.V_SALES_ORDER_HDR_CORE soh
    INNER JOIN 
      YUKENDHIRAN.ORDER_ANALYSIS.V_CUSTOMER_CORE cu 
    ON 
      soh.CUSTOMER_ID = cu.CUSTOMER_ID
  ) coc 
LEFT JOIN 
  YUKENDHIRAN.ORDER_XFRM.V_PROMOTION p 
ON 
  coc.CATEGORY = p.CUSTOMER_CATEGORY 
AND 
  (coc.COUPON IS NULL OR p.PROMOTION_TYPE = coc.COUPON)
WHERE 
  p.PROMOTION_TYPE IS NOT NULL
AND
  p.PROMOTION_TYPE != 'LOYALTY'
$$;
