CREATE VIEW IF NOT EXISTS Y_SIM_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE AS
SELECT
    INPUT_ITEM_ID,
    ITEM_CLASS_NM,
    OUTPUT_ITEM_ID,
    BOM_NUM,
    LOC
FROM
    Y_SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE;
