CREATE 
OR REPLACE VIEW YUKENDHIRAN.ORDER_XFRM.V_PROMOTION AS 
SELECT 
  PROMOTION_ID, 
  CUSTOMER_CATEGORY, 
  PROMOTION_TYPE, 
  PROMOTION_VALUE, 
  COMMENT 
FROM 
  YUKENDHIRAN.ORDER_BASE.T_PROMOTION;
  