CREATE 
OR REPLACE PROCEDURE PURCHASE_BASE.P_PURCHASE_HDR_CORE() RETURNS VARCHAR AS $$ BEGIN CREATE 
OR REPLACE VIEW PURCHASE_ANALYSIS.V_PURCHASE_DETAIL_CORE AS 
SELECT 
  * 
FROM 
  PURCHASE_ANALYSIS.V_PURCHASE_HDR_CORE 
WHERE 
  REQUEST_DATE > CURRENT_DATE 
  AND PLANT_LOCATION = 'INDIA' 
  AND SUPPLIER_CONFIRM_DATE < DATEADD(DAY, 90, CURRENT_DATE);
RETURN 'SUCCESS';
END;
$$;
CALL PURCHASE_BASE.P_PURCHASE_HDR_CORE();
SELECT 
  * 
FROM 
  PURCHASE_ANALYSIS.V_PURCHASE_HDR;