CREATE 
TABLE IF NOT EXISTS YUKENDHIRAN.ORDER_BASE.T_SALES_ORDER_HEADER (
  ORDER_ID VARCHAR(100), 
  ORDER_DATE DATE, 
  STATUS VARCHAR(100), 
  CUSTOMER_ID VARCHAR(100), 
  ITEM_COUNT INTEGER DEFAULT 0, 
  TOTAL_AMOUNT NUMBER(12, 2) DEFAULT 0, 
  DISCOUNT NUMBER(10, 2) DEFAULT 0, 
  COUPON VARCHAR(100),
  CREATE_DATE DATE, 
  CREATE_USER VARCHAR(100)
);
