CREATE 
TABLE IF NOT EXISTS YUKENDHIRAN.ORDER_BASE.T_PROMOTION (
  PROMOTION_ID VARCHAR(100), 
  CUSTOMER_CATEGORY VARCHAR(100), 
  PROMOTION_TYPE VARCHAR(100), 
  PROMOTION_VALUE NUMBER(10, 2), 
  COMMENT VARCHAR(200)
);
