INSERT INTO YUKENDHIRAN.ORDER_BASE.T_SALES_ORDER_DETAIL (
  ORDER_ID, 
  ORDER_DATE, 
  CUSTOMER_ID, 
  ITEM_ID, 
  QTY, 
  PRICE, 
  CREATE_DATE, 
  CREATE_USER
)
WITH Items AS (
  SELECT 
    'ITEM001' AS ITEM_ID, 10.0 AS ITEM_PRICE UNION ALL
  SELECT 
    'ITEM002', 20.0 UNION ALL
  SELECT 
    'ITEM003', 30.0 UNION ALL
  SELECT 
    'ITEM004', 40.0 UNION ALL
  SELECT 
    'ITEM005', 50.0
),
OrderItems AS (
  SELECT 
    h.ORDER_ID,
    h.ORDER_DATE,
    h.CUSTOMER_ID,
    i.ITEM_ID,
    UNIFORM(1, 11, RANDOM())::INT AS QTY, -- Random quantity between 1 and 10
    i.ITEM_PRICE AS PRICE,
    h.CREATE_DATE,
    h.CREATE_USER,
    ROW_NUMBER() OVER (PARTITION BY h.ORDER_ID ORDER BY SEQ4()) AS ITEM_SEQ
  FROM 
    YUKENDHIRAN.ORDER_BASE.T_SALES_ORDER_HEADER h
  CROSS JOIN 
    Items i
  QUALIFY ROW_NUMBER() OVER (PARTITION BY h.ORDER_ID ORDER BY SEQ4()) <= 3 -- Limit to 3 items per order
)
SELECT 
  ORDER_ID, 
  ORDER_DATE, 
  CUSTOMER_ID, 
  ITEM_ID, 
  QTY, 
  PRICE, -- Calculate total price
  CREATE_DATE, 
  CREATE_USER
FROM 
  OrderItems;
