CREATE 
OR REPLACE VIEW PURCHASE_ANALYSIS.V_PURCHASE_PLAN AS 
SELECT 
  ph.*, 
  pr.PRIORITY_RANK, 
  pr.PROCUREMENT_COST 
FROM 
  TABLE(
    PURCHASE_BASE.F_PURCHASE_SUPPLIER_RANK()
  ) pr 
  INNER JOIN PURCHASE_ANALYSIS.V_PURCHASE_DETAIL_CORE ph ON ph.SUPPLIER_ID = pr.SUPPLIER_ID;
SELECT 
  * 
FROM 
  PURCHASE_ANALYSIS.V_PURCHASE_PLAN;