CREATE 
OR REPLACE VIEW PURCHASE_ANALYSIS.V_PURCHASE_HDR_CORE AS 
SELECT 
  ph.PURCHASE_ORDER_NBR, 
  ph.SUPPLIER_ID, 
  ph.PLANT_LOCATION, 
  ph.TOTAL_QTY, 
  ph.TOTAL_AMOUNT, 
  ph.REQUEST_DATE, 
  ph.SUPPLIER_CONFIRM_DATE, 
  ph.CREATE_DATE, 
  ph.CREATE_USER, 
  pod.ITEM_ID, 
  pod.ORDER_QTY, 
  pod.PROCUREMENT_COST, 
FROM 
  PURCHASE_XFRM.V_PURCHASE_HDR ph 
  JOIN PURCHASE_XFRM.V_PURCHASE_DETAIL pod ON ph.SUPPLIER_ID = pod.SUPPLIER_ID;
SELECT 
  * 
FROM 
  PURCHASE_ANALYSIS.V_PURCHASE_HDR_CORE;