CREATE 
OR REPLACE VIEW PURCHASE_XFRM.V_PURCHASE_HDR AS 
SELECT 
  po.PURCHASE_ORDER_NBR, 
  po.SUPPLIER_ID, 
  po.PLANT_LOCATION, 
  po.TOTAL_QTY, 
  po.TOTAL_AMOUNT, 
  po.REQUEST_DATE, 
  po.REQUEST_DATE + s.LEAD_TIME AS SUPPLIER_CONFIRM_DATE, 
  po.CREATE_DATE, 
  po.CREATE_USER 
FROM 
  PURCHASE_BASE.T_PURCHASE_ORDER_HDR po 
  JOIN PURCHASE_BASE.T_SUPPLIER_HDR s ON po.SUPPLIER_ID = s.SUPPLIER_ID;
SELECT 
  * 
FROM 
  PURCHASE_XFRM.V_PURCHASE_HDR;