CREATE 
OR REPLACE TABLE ORDER_BASE.T_CUSTOMER (
  CUSTOMER_ID VARCHAR(100), 
  ADDRESS VARCHAR(500), 
  PHONE_NO VARCHAR(100), 
  CATEGORY VARCHAR(100), 
  STATUS VARCHAR(100), 
  TOTAL_ORDERS INTEGER DEFAULT 0, 
  TOTAL_INVOICE_AMOUNT NUMBER(12, 2) DEFAULT 0, 
  LOYALTY_POINTS INTEGER DEFAULT 0, 
  CREATE_DATE DATE, 
  CREATE_USER VARCHAR(100)
);
