UPDATE ORDER_BASE.T_SALES_ORDER_DETAIL
SET TOTAL_AMOUNT = 0;
UPDATE ORDER_BASE.T_SALES_ORDER_HEADER
SET TOTAL_AMOUNT = 0,
    DISCOUNT = 0,
    ITEM_COUNT = 0;
UPDATE ORDER_BASE.T_CUSTOMER
SET TOTAL_ORDERS = 0
    TOTAL_INVOICE_AMOUNT = 0,
    LOYALTY_POINTS = 0;
TRUNCATE TABLE ORDER_BASE.T_INVOICE;