SELECT 
  CUSTOMER_ID, 
  STATUS 
FROM 
  ORDER_BASE.T_CUSTOMER 
WHERE 
  STATUS = 'ACTIVE';
SELECT 
  ORDER_ID, 
  CUSTOMER_ID, 
  STATUS 
FROM 
  ORDER_BASE.T_SALES_ORDER_HEADER 
WHERE 
  STATUS = 'ACTIVE';
SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID
FROM
    ORDER_BASE.T_SALES_ORDER_HEADER
WHERE
    ORDER_DATE > CURRENT_DATE;
SELECT 
  cu.CUSTOMER_ID, 
  soh.ORDER_ID, 
  soh.DISCOUNT, 
  cu.CATEGORY, 
  cu.LOYALTY_POINTS, 
  inv.FINAL_INVOICE_AMT, 
  inv.TAX_AMOUNT, 
  soh.TOTAL_AMOUNT 
FROM 
  ORDER_BASE.T_CUSTOMER cu 
  JOIN ORDER_BASE.T_SALES_ORDER_HEADER soh ON cu.CUSTOMER_ID = soh.CUSTOMER_ID 
  JOIN ORDER_BASE.T_INVOICE inv ON soh.ORDER_ID = inv.ORDER_ID 
WHERE 
  cu.STATUS = 'ACTIVE' 
  AND soh.STATUS = 'ACTIVE';
